### ISSUE TITLE
AWS AssumeRoleWithWebIdentity support

### ISSUE THREAD

**Issue by jclarysse** [bakdata/kafka-large-message-serde#20]
Hi, I'm using the Serde with Kafka Connect, AWS S3 and STS [AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html). It works properly, however I now have the requirement to move to [AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html). Is that perhaps something that you plan for next releases? If not, are you open to external contributions?

**Comment by raminqaf** [comment]
@philipp94831 Closing the issue because of #21
