### ISSUE TITLE
Optimize memory usage

### ISSUE THREAD

**Issue by TomBillietKlarrio** [bakdata/kafka-large-message-serde#32]
At the moment the data is prefixed on kafka with a "magic byte" that indicates whether the data is stored on kafka or not. However, to be able to do so, a byte array needs to be allocated twice, once for the raw data, and once for the raw data + magic byte. Since we're looking at this project to process messages that are potentially over 100mb big, such an extra allocation can be painful.

What I want to suggest (and I'm happy to submit a PR for this):
* Instead of prepending the message with a magic byte, use a header on kafka to store this info.
* Make this a configuration flag which is off by default to not break things.

Added bonus is that messages that are not send to the large-message-store can be read by any app/console-consumer with the default serializer you use.

**Comment by philipp94831** [comment]
Hi @TomBillietKlarrio, I was not aware that Kafka serializers have access to the record headers (guess I should read the docs). Also Avro serializer does not use headers but rather magic bytes which did not lead us to questioning that decision...

Your idea sounds great, especially if it is a configurable feature. Feel free to submit a PR and we will review it as soon as possible

**Comment by philipp94831** [comment]
@TomBillietKlarrio The changes required for this are actually quite large. I think it will be better if we implement it ourselves. I expect it to be ready some time next week

**Comment by TomBillietKlarrio** [comment]
I expected it to be fairly small actually. But you'll be able to estimate better.
Fine for me too, I first had some other fixes I need to do anyway. Much appreciated!

**Comment by TomBillietKlarrio** [comment]
Cool, thanks for the effort.

**Comment by philipp94831** [comment]
Hi @TomBillietKlarrio, we just released version 2.2.0 which adds a new config `large.message.use.headers`. If you enable it, your problem should be solved

**Comment by TomBillietKlarrio** [comment]
Just tested it and works fine.

**Comment by TomBillietKlarrio** [comment]
Thanks for the heads-up. Took in the new version.
